### PR TITLE
Enable use of .env file to set service uid/gid in Docker Compose

### PR DESCRIPTION
**Pull request by ramen**
This change enables the use of .env files to avoid having to change the Docker Compose configs to set up file system permissions on Linux.

### CODE REVIEW

**Comment by mikeylove** [comment]
docker compose reads `.env` automatically?

**Comment by smrl** [comment]
Looks like you can pass it in as a command line parameter or specify it in
the config file
https://docs.docker.com/compose/environment-variables/set-environment-variables/#use-the-env_file-attribute

**Comment by ramen** [comment]
> docker compose reads `.env` automatically?

Yep. No further configuration is needed.

**Comment by ramen** [comment]
> Looks like you can pass it in as a command line parameter or specify it in the config file https://docs.docker.com/compose/environment-variables/set-environment-variables/#use-the-env_file-attribute

You can, but this is for additional/alternative env files besides .env

**Review by mikeylove — APPROVED** [review]
:shipit:

**Pull request merged**
